# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Laojie
tagline:          'Laojie.TK'
description:      'Welcome to <a href="http://Laojie.TK" target="_blank">Laojie.TK</a>.'
url:              http://Laojie.TK

author:
  name:           'Laojie'
  url:            https://Laojie.TK

paginate:         5

# Custom vars
version:          1.0.0
