# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            JoyBus-欢乐巴士
tagline:          'JoyBus.TK'
description:      'Welcome to <a href="http://Laojie.TK" target="_blank">JoyBus.TK</a>.'
url:              http://JoyBus.TK

author:
  name:           'JoyBus'
  url:            https://JoyBus.TK

paginate:         5

# Custom vars
version:          1.0.0
